- id: draw-2025-heatmap
  name: draw 2025 yearly heatmap
  entry: python daily_challenge/__init__.py
  language: python
  description: "Generate the 2025 yearly heatmap and stage the generated image."
  additional_dependencies: ['matplotlib', 'numpy']
